package UI;

import Bean.Photo;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class MultimediaApp extends javax.swing.JFrame {
    private ArrayList<Photo> Photos;
    private File[] images;
    private JLabel[] label;
    private int index;
            
    public MultimediaApp() {
        initComponents();
        Photos = new ArrayList<>();
        showImagesInFolder(new File("C:\\Users\\SVE14112EG\\Github\\RemoteControlMP\\Remote Control\\Photos"));
        showImage(Photos.get(0).getImage());
        index = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        allThumbnails = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        imageViewer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(allThumbnails);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 720, 100));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Multimedia Application");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 710, 50));
        getContentPane().add(imageViewer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 720, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public void showImagesInFolder (File folder) {
        Image thumbnail = null;
        images = folder.listFiles();
        label = new JLabel[images.length];
        for(int i = 0; i < images.length; i++) {
            String imgPath = images[i].getAbsolutePath();
            int index = imgPath.lastIndexOf('\\');
            String name = imgPath.substring(index+1);
            if(name.endsWith("jpg")) {
                Photo photo = new Photo(name, imgPath);
                Photos.add(photo);
                thumbnail = photo.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(thumbnail);
                label[i] = new JLabel();
                label[i].setIcon(icon);
                label[i].setText("");
                allThumbnails.add(label[i]);
                allThumbnails.repaint();
                allThumbnails.updateUI();
            }
        }
    }
    
    public void showImage(Image img) {
        ImageIcon icon = new ImageIcon(img);
        imageViewer.setIcon(icon);
    }
    
    public void nextImage() {
        index++;
        System.out.println(index);
        showImage(Photos.get(index).getImage());
    }
    
    public void prevImage() {
        index--;
        showImage(Photos.get(index).getImage());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allThumbnails;
    private javax.swing.JLabel imageViewer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
