package UI;

import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class RemoteControl extends javax.swing.JFrame {
    DatagramSocket clientSocket;
    InetAddress IPAddress;
    
    public RemoteControl(DatagramSocket _clientSocket, InetAddress _IPAddress) {
        initComponents();
        clientSocket = _clientSocket;
        IPAddress = _IPAddress;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        slideshowBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        timeSlider = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(160, 250));
        setPreferredSize(new java.awt.Dimension(150, 220));
        setResizable(false);
        setSize(new java.awt.Dimension(150, 220));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeBtn.setBackground(new java.awt.Color(255, 51, 51));
        closeBtn.setFont(new java.awt.Font("Calibri Light", 1, 15)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(255, 0, 0));
        closeBtn.setText("X");
        closeBtn.setBorder(null);
        closeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closeBtn.setOpaque(false);
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -1, 20, 30));

        backBtn.setFont(new java.awt.Font("Calibri Light", 1, 15)); // NOI18N
        backBtn.setText("Back");
        backBtn.setBorder(null);
        backBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backBtn.setOpaque(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, 40));

        nextBtn.setFont(new java.awt.Font("Calibri Light", 1, 15)); // NOI18N
        nextBtn.setText("Next");
        nextBtn.setBorder(null);
        nextBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextBtn.setOpaque(false);
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 60, 40));

        slideshowBtn.setFont(new java.awt.Font("Calibri Light", 1, 15)); // NOI18N
        slideshowBtn.setText("Start Slideshow");
        slideshowBtn.setBorder(null);
        slideshowBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slideshowBtn.setOpaque(false);
        slideshowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slideshowBtnActionPerformed(evt);
            }
        });
        getContentPane().add(slideshowBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, 40));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Universal Remote");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 150, 40));
        getContentPane().add(timeSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        try {
            request("Next");
        } catch (Exception ex) {
            Logger.getLogger(RemoteControl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void slideshowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slideshowBtnActionPerformed
        try {
            request("Slideshow");
        } catch (Exception ex) {
            Logger.getLogger(RemoteControl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_slideshowBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        try {
            request("Back");
        } catch (Exception ex) {
            Logger.getLogger(RemoteControl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        try {
            request("Close");
            clientSocket.close();
            dispose();
            System.exit(0);
        } catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_closeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void request(String request) throws Exception {
        byte[] sendRequest = new byte[4];        
        /*int diff = sendRequest.length - request.length();
        while(diff > 0) {
            request += " ";
            diff--;
        }*/
        sendRequest = request.getBytes();   
        DatagramPacket sendPacket = new DatagramPacket(sendRequest, sendRequest.length, IPAddress, 9876);       
        clientSocket.send(sendPacket);  
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton slideshowBtn;
    private javax.swing.JSlider timeSlider;
    // End of variables declaration//GEN-END:variables
}
